use rakit_ir_hir::ty::TypeInfo;
use crate::{RakitExport, RakitStruct};

/// Generate C header file dari fungsi Rakit yang di-export.
pub struct CBindingGenerator {
    pub functions: Vec<RakitExport>,
    pub structs: Vec<RakitStruct>,
}

impl CBindingGenerator {
    pub fn new(functions: Vec<RakitExport>, structs: Vec<RakitStruct>) -> Self {
        CBindingGenerator { functions, structs }
    }

    pub fn generate_header(&self) -> String {
        let mut header = String::new();

        header.push_str("/* ============================================\n");
        header.push_str(" *  Header Rakit — Generated by rakit-polyglot\n");
        header.push_str(" *  Jangan edit manual — regenerate via:\n");
        header.push_str(" *    rakit polyglot file.rakit --lang c\n");
        header.push_str(" * ============================================ */\n\n");

        header.push_str("#ifndef _RAKIT_BINDINGS_H_\n");
        header.push_str("#define _RAKIT_BINDINGS_H_\n\n");
        header.push_str("#include <stdint.h>\n");
        header.push_str("#include <stdbool.h>\n\n");

        for s in &self.structs {
            header.push_str(&self.generate_struct(s));
            header.push('\n');
        }

        for f in &self.functions {
            header.push_str(&self.generate_function_decl(f));
            header.push_str(";\n\n");
        }

        header.push_str("#endif /* _RAKIT_BINDINGS_H_ */\n");
        header
    }

    fn generate_struct(&self, s: &RakitStruct) -> String {
        let mut out = format!("typedef struct {{\n");
        for field in &s.fields {
            let c_type = self.rakit_to_c_type(&field.ty);
            out.push_str(&format!("    {} {};\n", c_type, field.name));
        }
        out.push_str(&format!("}} {};\n", s.name));
        out
    }

    fn generate_function_decl(&self, f: &RakitExport) -> String {
        let return_c = self.rakit_to_c_type(&f.return_ty);
        let mut out = format!("{} {}", return_c, f.c_name());

        out.push('(');
        for (i, param) in f.params.iter().enumerate() {
            if i > 0 { out.push_str(", "); }
            let c_type = self.rakit_to_c_type(&param.ty);
            out.push_str(&format!("{} {}", c_type, param.name));
        }
        out.push(')');

        out
    }

    fn rakit_to_c_type(&self, ty: &TypeInfo) -> &'static str {
        match ty {
            TypeInfo::I32 => "int32_t",
            TypeInfo::I64 => "int64_t",
            TypeInfo::U32 => "uint32_t",
            TypeInfo::U64 => "uint64_t",
            TypeInfo::F32 => "float",
            TypeInfo::F64 => "double",
            TypeInfo::Bool => "bool",
            TypeInfo::String => "const char*",
            TypeInfo::Void => "void",
            TypeInfo::Node => "void*",
            TypeInfo::Array(_) => "void*",
            TypeInfo::Optional(_) => "void*",
            _ => "void*",
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{RakitParam, RakitExport};

    #[test]
    fn test_generate_header_empty() {
        let gen = CBindingGenerator::new(vec![], vec![]);
        let header = gen.generate_header();
        assert!(header.contains("#ifndef _RAKIT_BINDINGS_H_"));
        assert!(header.contains("#endif"));
    }

    #[test]
    fn test_generate_header_with_function() {
        let f = RakitExport {
            name: "hitung".into(),
            params: vec![RakitParam { name: "x".into(), ty: TypeInfo::I32 }],
            return_ty: TypeInfo::I32,
            is_async: false,
        };
        let gen = CBindingGenerator::new(vec![f], vec![]);
        let header = gen.generate_header();
        assert!(header.contains("int32_t rakit_hitung(int32_t x)"));
    }
}
