use rakit_ir_hir::ty::TypeInfo;
use crate::RakitExport;

/// Generate Python bindings (ctypes) untuk fungsi Rakit yang di-export.
pub struct PythonBindingGenerator;

impl PythonBindingGenerator {
    pub fn generate_py_module(&self, exports: &[RakitExport]) -> String {
        let mut code = String::new();

        code.push_str("\"\"\"\n");
        code.push_str("Modul Python — Generated by rakit-polyglot\n");
        code.push_str("Gunakan: import nama_modul\n");
        code.push_str("\"\"\"\n\n");

        code.push_str("import ctypes\n");
        code.push_str("import os\n\n");

        code.push_str("_lib = ctypes.CDLL(os.path.join(os.path.dirname(__file__), '_rakit_native.dll'))\n\n");

        for f in exports {
            code.push_str(&self.generate_wrapper(f));
            code.push('\n');
        }

        code
    }

    fn generate_wrapper(&self, f: &RakitExport) -> String {
        let params_str = f.params.iter()
            .map(|p| format!("{}: str", p.name))
            .collect::<Vec<_>>()
            .join(", ");

        let mut wrapper = format!("def {}({}) -> {}:\n", f.name, params_str, self.doc_str(&f.return_ty));

        wrapper.push_str("    \"\"\"\n");
        wrapper.push_str(&format!("    {} — dipanggil dari Rakit\n", f.name));
        if !f.params.is_empty() {
            wrapper.push_str("    Args:\n");
            for p in &f.params {
                wrapper.push_str(&format!("        {}: {}\n", p.name, self.doc_str(&p.ty)));
            }
        }
        wrapper.push_str("    Returns:\n");
        wrapper.push_str(&format!("        {}\n", self.doc_str(&f.return_ty)));
        wrapper.push_str("    \"\"\"\n");

        wrapper.push_str("    _lib.");
        wrapper.push_str(&f.c_name());
        wrapper.push_str(".argtypes = [");
        for p in &f.params {
            wrapper.push_str(&format!("{}, ", self.py_type(&p.ty)));
        }
        wrapper.push_str("]\n");

        wrapper.push_str("    _lib.");
        wrapper.push_str(&f.c_name());
        wrapper.push_str(".restype = ");
        wrapper.push_str(&self.py_type(&f.return_ty));
        wrapper.push('\n');

        wrapper.push_str(&format!("    _result = _lib.{}(\n", f.c_name()));
        for p in &f.params {
            wrapper.push_str(&format!("        {}.encode('utf-8') if isinstance({}, str) else {},\n",
                p.name, p.name, p.name));
        }
        wrapper.push_str("    )\n");

        wrapper.push_str("    return _result\n");

        wrapper
    }

    fn doc_str(&self, ty: &TypeInfo) -> &'static str {
        match ty {
            TypeInfo::I32 | TypeInfo::I64 => "int",
            TypeInfo::F32 | TypeInfo::F64 => "float",
            TypeInfo::Bool => "bool",
            TypeInfo::String => "str",
            TypeInfo::Void => "None",
            _ => "object",
        }
    }

    fn py_type(&self, ty: &TypeInfo) -> &'static str {
        match ty {
            TypeInfo::I32 | TypeInfo::I64 => "ctypes.c_int32",
            TypeInfo::U32 | TypeInfo::U64 => "ctypes.c_uint32",
            TypeInfo::F32 => "ctypes.c_float",
            TypeInfo::F64 => "ctypes.c_double",
            TypeInfo::Bool => "ctypes.c_bool",
            TypeInfo::String => "ctypes.c_char_p",
            TypeInfo::Void => "None",
            _ => "ctypes.c_void_p",
        }
    }
}
