use rakit_ir_hir::ty::TypeInfo;
use crate::RakitExport;

/// Generate Rust FFI bindings untuk fungsi Rakit yang di-export.
pub struct RustBindingsGenerator;

impl RustBindingsGenerator {
    pub fn generate_rust_module(&self, exports: &[RakitExport]) -> String {
        let mut code = String::new();

        code.push_str("//! Rust FFI bindings — Generated by rakit-polyglot\n");
        code.push_str("//! Gunakan:\n");
        code.push_str("//! ```rust\n");
        code.push_str("//! #[link(name = \"rakit_native\")]\n");
        code.push_str("//! extern \"C\" {\n");
        for f in exports {
            code.push_str(&format!("//!     {};\n", self.generate_extern_decl(f)));
        }
        code.push_str("//! }\n");
        code.push_str("//! ```\n\n");

        code.push_str("#![allow(non_camel_case_types, dead_code)]\n\n");
        code.push_str("use std::ffi::{CStr, CString};\n");
        code.push_str("use std::os::raw::{c_char, c_int, c_double, c_float};\n\n");

        for f in exports {
            code.push_str(&self.generate_safe_wrapper(f));
            code.push('\n');
        }

        code
    }

    fn generate_extern_decl(&self, f: &RakitExport) -> String {
        let ret_str = self.rust_type(&f.return_ty);
        let params_str: Vec<String> = f.params.iter()
            .map(|p| format!("{}: {}", p.name, self.rust_type(&p.ty)))
            .collect();
        format!("fn {}({}) -> {}", f.c_name(), params_str.join(", "), ret_str)
    }

    fn generate_safe_wrapper(&self, f: &RakitExport) -> String {
        let mut code = String::new();

        code.push_str(&format!("pub fn {}(", f.name));
        let params_str: Vec<String> = f.params.iter()
            .map(|p| format!("{}: {}", p.name, self.safe_rust_type(&p.ty)))
            .collect();
        code.push_str(&params_str.join(", "));
        code.push_str(") -> ");
        code.push_str(&self.safe_rust_type(&f.return_ty));
        code.push_str(" {\n");

        code.push_str("    unsafe {\n");

        code.push_str(&format!("        {}(\n", f.c_name()));
        for p in &f.params {
            code.push_str(&format!("            {}.as_ptr(),\n", p.name));
        }
        code.push_str("        )\n");

        code.push_str("    }\n");
        code.push_str("}\n");

        code
    }

    fn rust_type(&self, ty: &TypeInfo) -> &'static str {
        match ty {
            TypeInfo::I32 => "c_int",
            TypeInfo::I64 => "i64",
            TypeInfo::U32 => "u32",
            TypeInfo::U64 => "u64",
            TypeInfo::F32 => "c_float",
            TypeInfo::F64 => "c_double",
            TypeInfo::Bool => "bool",
            TypeInfo::String => "*const c_char",
            TypeInfo::Void => "()",
            TypeInfo::Node => "*mut std::ffi::c_void",
            TypeInfo::Array(_) => "*const c_char",
            TypeInfo::Optional(_) => "*const c_char",
            _ => "*const c_char",
        }
    }

    fn safe_rust_type(&self, ty: &TypeInfo) -> &'static str {
        match ty {
            TypeInfo::String => "&str",
            TypeInfo::I32 => "i32",
            TypeInfo::I64 => "i64",
            TypeInfo::F32 => "f32",
            TypeInfo::F64 => "f64",
            TypeInfo::Bool => "bool",
            TypeInfo::Void => "()",
            _ => "&str",
        }
    }
}
